### ISSUE TITLE
No valid characters in Header name not checked

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#10]
Heading TEST_D-H should not be allowed.
[4.1-rule19a-2.zip](https://github.com/asitha-sena/python-ags4/files/5900362/4.1-rule19a-2.zip)

**Comment by asitha-sena** [comment]
Check for Rule 19a improved in v0.3.4. This error should be caught now.

**Comment by Rogerchandler** [comment]
error picked up correctly in V0.3.4
