### ISSUE TITLE
Invalid header name not checked

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#11]
According to Rule 19b the header name NAME_VAL is not allowed.  I think this is a minor problem as I have never seen this but it is in the rules!

Should include a check that the group name used exists.  In this case above NAME is a group that does not exist.

[4.1-rule19b-1.zip](https://github.com/asitha-sena/python-ags4/files/5900375/4.1-rule19b-1.zip)

**Comment by asitha-sena** [comment]
I can add this check. But don't fields like SPEC_REF, SPEC_DPTH, and TEST_STAT which are in the standard dictionary also infringe this rule since there is no SPEC or TEST group?

**Comment by Rogerchandler** [comment]
good point.  I suggest we could add a rule that checks that the group name for a new field is an existing group or "TEST" or "SPEC" - these are the only two rule-breakers in the standard dictionary.

**Comment by asitha-sena** [comment]
Check added to v0.3.5.
