### ISSUE TITLE
Rule 20 checks not working

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#12]
Attached are 4 examples - 1 that works and 3 that have errors (See TRAN record for error information).

All 4 files fail with FILE parent problems (FILE does not have any parents).
[Rule20examples.zip](https://github.com/asitha-sena/python-ags4/files/5900419/Rule20examples.zip)

**Comment by asitha-sena** [comment]
Check for Rule 20 added in v0.3.4.

**Comment by Rogerchandler** [comment]
all checks passed in V0.3.4
