### ISSUE TITLE
A null record in TRAN_DLIM causes a crash.

### ISSUE THREAD

**Issue by Didymograptus** [asitha-sena/python-ags4#14]
Rule 11a states:

>Each GROUP/KEY FIELD shall be separated by a delimiter character. This single delimiter character shall be defined in TRAN_DLIM. The default being "|" (ASCII character 124).

An interpretation of the rule is that TRAN_DLIM shall be defined, i.e. not a null, however if it is not used it is often omitted. 

I suggest that a warning be reported if no data item TRAN_DLIM data is included and the file does not use the delimiter and a error is reported if the TRAN_DLIM data item has been omitted and a delimiter character is used (difficult to check if other than "|")??.
 
[4.1-rule11a.ags.zip](https://github.com/asitha-sena/python-ags4/files/5905725/4.1-rule11a.ags.zip)

**Comment by asitha-sena** [comment]
I ran the attached example file using v0.3.3 without crashing as shown in the screenshot. Can you please confirm whether upgrading to v0.3.3 works for you?

![Screenshot from 2021-02-04 21-07-45](https://user-images.githubusercontent.com/8764587/106979876-324c9100-672d-11eb-8f8d-9ab9d130d281.png)

I'll change the error message to a warning if TRAN_DLIM is left blank in files without record links.

**Comment by Didymograptus** [comment]
v0.3.3 works fine. excellent.
