### ISSUE TITLE
LBSG, TREM and STND incorrectly finds errors

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#15]
LBSG does not require a parent group but this checker reports this as an error.
[LBSGCheck.zip](https://github.com/asitha-sena/python-ags4/files/5938761/LBSGCheck.zip)

**Comment by Rogerchandler** [comment]
Same problem with STND and TREM

[STNDandTREMCheck.zip](https://github.com/asitha-sena/python-ags4/files/5938952/STNDandTREMCheck.zip)

**Comment by asitha-sena** [comment]
Check added to v0.3.5.
