### ISSUE TITLE
Standard header defined in DICT - error missed

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#16]
If the DICT table has a standard field defined then the order of the columns in the table cannot be determined.  The attached example has a field that is already defined added to the table which is in breach of rule 9

[4.1-rule9 -1.zip](https://github.com/asitha-sena/python-ags4/files/5938878/4.1-rule9.-1.zip)

**Comment by asitha-sena** [comment]
The attached file did not give any errors with v0.3.4. Fields in the DICT table that are already defined in the Standard Dictionary are ignored. The check for Rule 9 always gives precedence to the order of columns as defined in the Standard Dictionary. Is that not sufficient?
