### ISSUE TITLE
AGS 3.1 file

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#17]
If an AGS 3.1 file is selected then each line in the file is returned as an error line as it does not have the data descriptor.

AGS 3.1 is out of scope for this project at the moment I suggest a check is added to see if the first non-blank
[AGS3.zip](https://github.com/asitha-sena/python-ags4/files/5938927/AGS3.zip)
 line starts with "** and if so then report in the error file that the file is an AGS 3 file and checking is not currently supported for this file type.

**Comment by Didymograptus** [comment]
Not sure if AGS3.1 should ever be in scope? Isn't the scope implied by the name of the library i.e. AGS4? N.B. python-ags4 is a library, not an application.

IMHO AGS3.1 is a separate library. 

If the phrase "checking is not **currently** supported" it implies that one day it will be. 

I suggest leave it at "checking is not supported".

**Comment by Rogerchandler** [comment]
**I suggest leave it at "checking is not _supported".**
I'm happy with that and agree that AGS 3.1 is out of scope for an AGS 4 checker.  

Many users would not know the difference when they upload an AGS file so it is important that we tell them that their file is not supported rather than give them an error message for each line.

**Comment by asitha-sena** [comment]
I also agree that checks for AGS3 is out of scope from the python_ags4 library. I added a general warning if an AGS3 like file is given as input. Please check v0.3.5.
