### ISSUE TITLE
Dev env

### ISSUE THREAD

**Issue by Didymograptus** [asitha-sena/python-ags4#19]
Asitha,

It would be really helpful if you could describe your testing/dev environment. e.g. what OS? what file structure for dev?

We could provide dev info in the wiki.

Cheers

Tony

**Comment by asitha-sena** [comment]
Tony,
Thanks for the suggestion. I added details of the dev environment to the Wiki page. Please have a look and let me know if I've missed anything.

**Comment by Didymograptus** [comment]
Asitha,

Thanks, that's great. It will be really useful.

Tony
