### ISSUE TITLE
null TRAN_RCON causes crash in checker

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#4]
A null record in TRAN_RCON causes a crash even if there are no concatenations used
[4.1-rule16b-5.zip](https://github.com/asitha-sena/python-ags4/files/5898524/4.1-rule16b-5.zip)

**Comment by asitha-sena** [comment]
Added two more except clauses to rule_16() to catch this error. Check whether this is resolved in v0.3.3.

**Comment by Rogerchandler** [comment]
Checked and passed
