### ISSUE TITLE
Checker crashes with output set and no errors

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#5]
When writing the output file for a file with no errors the program crashes as it tries to write an extended charset tick.  Can be repeated with any AGS file that does not have any errors.

**Comment by asitha-sena** [comment]
Removed tick mark from being printed to screen in v0.3.2. Let me know if this resolved the issue.

**Comment by Rogerchandler** [comment]
Tested and resolved.
