### ISSUE TITLE
No output file for no errors

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#6]
It is useful to have an output file to show clients that there were no errors.  At the moment the -o option only outputs a file if there were any errors so it is impossible to get a file that shows there were no errors.

Please add the output to file to say "No errors"

**Comment by asitha-sena** [comment]
Fixed in v0.3.4.

**Comment by Rogerchandler** [comment]
confirmed as fixed in V0.3.4
