### ISSUE TITLE
Meta data for Output file

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#7]
Suggestion:

Please add the following to the output file.  This can then be used as proof to a client that the file has been checked.

1) The filename of the file checked
2) The size of the file
3) The date/time the check was completed
4) The version number of the checker used

**Comment by asitha-sena** [comment]
Added in v0.3.4.

**Comment by Rogerchandler** [comment]
thank you for adding this.  Output files now included in tests directory for others to review
