### ISSUE TITLE
No Escaped Quotes

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#8]
Rule 5 states that Quotes in text must be escaped with quotes.

Attached file breaks this rule but checker says no errors.
[4.1-rule5-1.zip](https://github.com/asitha-sena/python-ags4/files/5899662/4.1-rule5-1.zip)

**Comment by asitha-sena** [comment]
Check for Rule 5 improved in v0.3.4. This error should be caught now.

**Comment by Rogerchandler** [comment]
Error checked with files 4.1-rule5 and 4.1-rule5-1 and passed.
