### ISSUE TITLE
Typo in error message for Rule 19b

### ISSUE THREAD

**Issue by Rogerchandler** [asitha-sena/python-ags4#9]
Rule 19b:
  Line 39	 TEST	 Heading TEST_DEPTH should consist of a 4 charater group name and a field name of upto 4 characters.

Should be

  Line 39	 TEST	 Heading TEST_DEPTH should consist of a 4 **character** group name and a field name of **up to** 4 characters.

**Comment by asitha-sena** [comment]
Typo fixed in v0.3.4.

**Comment by Rogerchandler** [comment]
Typo checked and passed in V0.3.4
